# Generated by Django 6.0.6 on 2026-06-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Librarian',
        ),
    ]
