# Generated by Django 6.0.6 on 2026-06-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_users_librarian'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='librarian',
            table='Librarian_details',
        ),
    ]
