# Generated by Django 6.0.6 on 2026-06-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_librarian_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='librarian',
            table='librarian_details',
        ),
    ]
