# Generated by Django 6.0.6 on 2026-06-10 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_librarian_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finemaintanence',
            old_name='user',
            new_name='librarian',
        ),
        migrations.RemoveField(
            model_name='member',
            name='book',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='finemaintanence',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='choice',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='IssueMaintanence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.bookdetails')),
                ('librarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.librarian')),
            ],
            options={
                'db_table': 'issue_maintanence',
            },
        ),
    ]
