# Generated by Django 6.0.6 on 2026-06-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_rename_user_finemaintanence_librarian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_shown',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_date',
            field=models.DateField(),
        ),
    ]
