# Generated by Django 6.0.6 on 2026-06-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_is_shown_alter_member_membership_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_shown',
        ),
        migrations.AddField(
            model_name='librarian',
            name='is_shown',
            field=models.BooleanField(default=True),
        ),
    ]
