# Generated by Django 6.0.6 on 2026-06-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_member_is_shown_librarian_is_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='is_acitve',
            field=models.BooleanField(default=True),
        ),
    ]
