# Generated by Django 6.0.6 on 2026-06-11 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_bookdetails_is_acitve'),
    ]

    operations = [
        migrations.AddField(
            model_name='finemaintanence',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
        migrations.AddField(
            model_name='issuemaintanence',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
        migrations.AddField(
            model_name='issuemaintanence',
            name='return_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='issuemaintanence',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
