# Generated by Django 6.0.6 on 2026-06-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_finemaintanence_member_issuemaintanence_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemaintanence',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
