# Generated by Django 6.0.6 on 2026-06-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_issuemaintanence_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemaintanence',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='issuemaintanence',
            name='issue_date',
            field=models.DateTimeField(),
        ),
    ]
