# Generated by Django 6.0.6 on 2026-06-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_issuemaintanence_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finemaintanence',
            name='paid_time',
            field=models.DateTimeField(),
        ),
    ]
