# Generated by Django 6.0.6 on 2026-06-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_finemaintanence_paid_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='finemaintanence',
            name='books_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuemaintanence',
            name='books_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
