# Generated by Django 6.0.6 on 2026-06-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_finemaintanence_books_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finemaintanence',
            name='paid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
