# Generated by Django 6.0.6 on 2026-06-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_finemaintanence_paid_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_expired',
            field=models.BooleanField(default=True),
        ),
    ]
