# Generated by Django 6.0.6 on 2026-06-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_member_is_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuemaintanence',
            old_name='issue_date',
            new_name='over_duedate',
        ),
    ]
