# Generated by Django 6.0.6 on 2026-06-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_rename_issue_date_issuemaintanence_over_duedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuemaintanence',
            old_name='over_duedate',
            new_name='issue_date',
        ),
        migrations.AddField(
            model_name='finemaintanence',
            name='overdue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
