# Generated by Django 6.0.6 on 2026-06-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_rename_over_duedate_issuemaintanence_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finemaintanence',
            name='overdue_date',
            field=models.DateField(),
        ),
    ]
