# Generated by Django 6.0.6 on 2026-06-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_alter_finemaintanence_overdue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
