# Generated by Django 6.0.6 on 2026-06-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_alter_member_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finemaintanence',
            name='paid_cost',
            field=models.IntegerField(null=True),
        ),
    ]
