# Generated by Django 6.0.6 on 2026-06-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_alter_finemaintanence_paid_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finemaintanence',
            name='overdue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
