# Generated by Django 6.0.6 on 2026-06-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_alter_finemaintanence_overdue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finemaintanence',
            name='paid_cost',
        ),
    ]
