# Generated by Django 6.0.6 on 2026-06-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_remove_finemaintanence_paid_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='finemaintanence',
            name='paid_cost',
            field=models.IntegerField(null=True),
        ),
    ]
