# Generated by Django 6.0.6 on 2026-06-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_finemaintanence_paid_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
