# Generated by Django 6.0.6 on 2026-06-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_rename_name_member_first_name_member_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='finemaintanence',
            name='remain_cost',
            field=models.IntegerField(null=True),
        ),
    ]
