# Generated by Django 6.0.6 on 2026-06-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
