# Generated by Django 6.0.6 on 2026-06-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_alter_librarian_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
