# Generated by Django 6.0.6 on 2026-07-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_alter_librarian_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='update_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
