# Generated by Django 6.0.6 on 2026-07-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_librarian_update_requested_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
